config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users
  resources :restaurants do
    resources :reviews
  end
  resources :categories
  root 'restaurants#index'
  get 'search', to: 'restaurants#search'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  belongs_to :user, optional: true
  belongs_to :category
  has_many :reviews
  has_attached_file :rest_img, styles: { rest_index: "250x300>", rest_show: "325x400>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :rest_img, content_type: /\Aimage\/.*\z/


  paginates_per 3
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_selet, only: [:new, :edit, :create]
  #before_action :set_search

  def index

       if params[:category].blank?
       @restaurants = Restaurant.all.order("created_at DESC").page(params[:page])

    else
       @category_id = Category.find_by(name: params[:category]).id
       @restaurants = Restaurant.where(:category_id => @category_id).order("created_at DESC").page(params[:page])
    end
end
def search
  @restaurants=Restaurant.where("Lower(name) LIKE ?", "%" + params[:q] + "%").page(params[:page])
end

  def show
      @restaurants= Restaurant.find(params[:id])
      if @restaurants.reviews.blank?
      @average_review = 0
     else
     @average_review = @restaurants.reviews.average(:rating).round(2)
    end
end

  def new
     @restaurants = current_user.restaurants.build
     #@categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
     @restaurants = current_user.restaurants.build(restaurant_params)
    # @restaurants.category_id = params[:category_id]
  if @restaurants .save
     # RestMailer.rest_mailer(@restaurant).deliver
      flash[:notice] = 'New Restaurant added'
      redirect_to root_path
    else
      render 'new'
   end
 end

 def edit
     @categories = Category.all.map{ |c| [c.name, c.id] }
 end

 def update
    #@restaurants.category_id = params[:category_id]
    if @restaurants.update(restaurant_params)
     redirect_to restaurant_path(@restaurants)
   else
     render 'edit'
 end
end

 def destroy
   @restaurants.destroy
   redirect_to root_path
 end
   private
   def restaurant_params
    params.require(:restaurant).permit(:name, :address,
                                       :description, :category_id,
                                       :rest_img, :q)
  end

  def find_restaurant
     @restaurants = Restaurant.find(params[:id])
  end

  def set_selet
     @categories = Restaurant.all.map{ |c| [c.name, c.id] }
  end
  def set_search
     @search = Restaurant.ransack(params[:q])
     @restaurants = @search.result
   end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurants, html: { multipart: true } do |form| %>
  <% if @restaurants.errors.any? %>
    <div id="error_explanation">
      <h2><%= @restaurants.errors.count %> are the errors.</h2>
      <ul>
      <% @restaurants.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :Category %>
    <%= form.collection_select :category_id, Category.all, :id, :name,
                       prompt: true, selected: @categories %>
  </div>

<div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>


  <div>
    <%= form.label :rest_img %>
    <%= form.file_field :rest_img %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="col-md-6 col-md-offset-3">

   <div class="edit-rest-form">

<h1>Edit Restaurant</h1>
   <%= simple_form_for @restaurants, :html => {:multipart => true} do |f| %>
   <%= f.select :category_id, @categories %>
   <%= f.file_field :rest_img %>
   <%= f.input :name, lable: "Restaurant Name"%>
   <%= f.input :address %>
   <%= f.input :description %>
   <%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

   </div>
 </div>

app/views/restaurants/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @restaurants.count == 0 %>

	<h1>There are no restaurant added in this category</h1>

<% else %>
<div class="owl-carousel">
<div class="row">
     <% @restaurants.each do |restaurant|%>
  <div class="col-md-3">
		   <h3><%= restaurant.name%></h3>
       <a href="/restaurants/<%= restaurant.id %>">click to review
       <%= image_tag restaurant.rest_img.url(:rest_index), class:"rest" %>
    </a>

     </div>
       <% end %>

  </div>
<% end %>
<%= paginate @restaurants %>

app/views/restaurants/new.html.erb
<div class="col-md-6 col-md-offset-3">

   <div class="new-rest-form">

     <h1>New Restaurant</h1>

     <%= render 'form' %>

     <%= link_to "Back to Home", root_path, class: "btn btn-custom" %>
     	<div class="links btn-group">

    </div>

</div>

app/views/restaurants/search.erb
<h2>Search result</h2>
<div class="owl-carousel">
<div class="row">
     <% @restaurants.each do |restaurant|%>
  <div class="col-md-3">
		   <h3><%= restaurant.name%></h3>
       <a href="/restaurants/<%= restaurant.id %>">click to review
       <%= image_tag restaurant.rest_img.url(:rest_index), class:"rest" %>
    </a>

     </div>
       <% end %>

  </div>
<%= paginate @restaurants %>

app/views/restaurants/show.html.erb
<div class="row">

	<div class="col-md-4">

		 <%= image_tag @restaurants.rest_img.url(:rest_index), class:"rest" %>

	</div>

	<div class="col-md-8">

		<div class="rest-info">

			<h2 class="rest-title"><%= @restaurants.name %></h2>
			<h3 class="rest-address"><span>Location</span> <%= @restaurants.address %></h3>
			<h2 class="avg-rating">Average Rating</h2>
			<div class="average-review-rating" data-score=<%= @average_review %>></div>
			<span class="number-of-reviews">Based on <%= @restaurants.reviews.count %> reviews</span>
			<p class="rest-desc"><%= @restaurants.description %></p>

		</div>
	</div>


</div>

<div class="row">

	<div class="col-md-4">

		<div class="reviews">

			<!-- Where the reviews/ratings will go -->
			<h1>Reviews</h1>
			<%= render @restaurants.reviews %>

			<div>
				<%= link_to "Add Review", new_restaurant_review_path(@restaurants), class: "btn-custom" %>
			</div>

		</div>

	</div>

</div>

<div class="links btn-group">

	<%= link_to "Back", root_path, class: "btn btn-custom" %>

	<% if user_signed_in? %>

		<% if @restaurants.user_id == current_user.id %>

			<%= link_to "Edit Restarant", edit_restaurant_path(@restaurants), class: "btn btn-custom" %>
			<% end %>

			<%# if @restaurants.user_id && current_user.admin == true %>
			<%= link_to "Delete Restaurant", restaurant_path(@restaurants), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>

		<% end %>
<%# end %>

</div>


<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>