config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users
  resources :restaurants do
    resources :reviews
  end
  resources :categories
  root 'restaurants#index'
  get 'search', to: 'restaurants#search'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant
  before_action :find_review, only:[:edit, :update, :destroy]
  before_action :authenticate_user!, only:[:new, :edit]
  def new
    @review = Review.new
    if current_user
    @review = Review.where(user_id: current_user.id, restaurant_id: params[:restaurant_id]).first_or_initialize
    if @review.id.present?
      redirect_to restaurant_path(@restaurant)
      flash[:notice] = 'multiple review not allowd'
    else
      render 'edit'
    end
  end
  end
  def create
    @review = Review.new(review_params)
    @review.restaurant_id = @restaurant.id
    @review.user_id = current_user.id
    if @review.save
      #ReviewMailer.review_mailer(@restaurant).deliver
      flash[:notice] = 'review created'
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
  end
end

 def edit
 end

 def update

   if @review.update(review_params)
			redirect_to restaurant_path(@restaurant)
		else
			render 'edit'
		end
 end
 def destroy
    @review.destroy
		redirect_to restaurant_path(@restaurant)
	end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
  def find_review
    @review = Review.find(params[:id])
  end


end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for([@restaurants, @restaurant.reviews.build]) do |f| %>
<div id="rating-form">
		<label>Rating</label>
	</div>
<%= f.input :comment %>
<%= f.button :submit, :class=> "btn-custom2" %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});

</script>

app/views/reviews/_review.html.erb
<div class="review">
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p class="review-comment"><%= review.comment %></p>

    <% if user_signed_in? %>

		<% if review.user_id == current_user.id %>
  <div class="links btn-group">

     <%= link_to "Edit", edit_restaurant_review_path(review.restaurant, review), class: "btn btn-custom" %>
     <%= link_to "Delete", restaurant_review_path(review.restaurant, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>

  </div>


     <% end %>

  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-review-form">
      <h1>Edit Review</h1>
      <%= simple_form_for([@restaurant, @review]) do |f| %>
      <div id="rating-form">
				<label>Rating</label>
      </div>
        <%= f.input :comment %>
		  	<%= f.button :submit, :class => "btn-custom2" %>
		    <% end %>
        <%= link_to "Back to Home", root_path, class: "btn btn-custom" %>
     </div>
  </div>
<script>
     	$('#rating-form').raty({
	  	path: '/assets/',
		  scoreName: 'review[rating]'
	   });
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

   <div class="new-review-form">

      <h1>New Review</h1>
      <%= render 'form' %>
   </div>
</div>