config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users
  resources :restaurants do
    resources :reviews
  end
  resources :categories
  root 'restaurants#index'
  get 'search', to: 'restaurants#search'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantReview</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.0.0/jquery.raty.min.js', 'data-turbolinks-track': 'reload' %>
  </head>
   <body>
     <footer class="footer">
         <p>©CopyrightMeklit@DIVEINTOCODE-2021 </p>
       </footer>

     <nav class="navbar navbar-default">
       <div class="container">
          <div class="navbar-header">
            <%= link_to "Restaurant Review", root_path, class:"navbar-brand" %>
            </div>
            <ul class="nav navbar-nav">
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% if user_signed_in? %>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %>
                 <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
              <% end %>
              <li> <%= link_to "Add category", new_category_path %>
            </ul>
            <ul class="nav navbar-nav">
            <li>
              <%= form_tag(search_path, :method => "get", class: 'navbar-form navbar-left') do %>
              <div class="input-group">
                <%= search_field_tag :q, params[:q], placeholder: "Restaurant Name", class: "form-control" %>
                <div class="input-group-btn">
                  <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
                </div>
              </div>
              <% end %>
            </li>
          </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories </a>
  			 	  <ul class="dropdown-menu" role="menu">
  					   	<% Category.all.each do |category| %>
  							<li class="<%= 'active' if params[:category] == category.name %>">
  								<%= link_to category.name, restaurants_path(category: category.name), class: "link" %>
              </li>
              <% end %>
            </ul>
          </li>

              <% if user_signed_in? %>
              <li><%= link_to "Add Restaurant", new_restaurant_path, class:"navbar-brand" %></li>
              <li><%= link_to "Profile", user_path(current_user.id) %></li>
              <% if current_user.admin? %>
              <li><%= link_to "Admin dashboard", rails_admin_path, class:"navbar-brand" %></li>


            <% end %>
            <% end %>



            </ul>
             <marquee width="30%" direction="right" height="50px">
              <p class="p">Welcome! to Restaurant review site</p>
             </marquee>

        </div>

      </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
   <div class="container">
    <%= yield %>


  </div>

  </body>

</html>